remote_theme: just-the-docs/just-the-docs

title: ATS External API Documentation
description: Documentation with sidebar
theme: just-the-docs

just_the_docs:
  logo: "https://asymbl-mo.my.salesforce.com/servlet/servlet.ImageServer?id=015UT00000En42Q&oid=00DDn000009Rfb8"
  show_downloads: false
  search_enabled: true

# Sidebar navigation
nav:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: API Docs
    url: /api-docs
  - title: FAQ
    url: /faq
